---
title: "P8105_hm1_kh3074"
output: github_document
---
```{r}
#import all the packages needed
library(tidyverse)
```

---

# Problem 1 
```{r}
p1_var1 = rnorm(10,mean = 0,sd = 1)
#create a random sample of size 10 from a standard Normal distribution
p1_var2 = p1_var1 > 0 
#create a logical vector indicating whether elements of the sample are greater than 0
p1_var3 = c('I','love','pancake','and','I','don\'t','know','what','I\'m','saying')
#create a character vector of length 10
p1_var4 = factor(c('old','young','baby','old','young','baby','old','young','baby','young'))
#a factor vector of length 10, with 3 different factor “levels”
p1_df = tibble(
  p1_var1,
  p1_var2,
  p1_var3,
  p1_var4
)
#put all the four variables in to a dataframe
p1_df
```
```{r}
for (i in 1:length(p1_df)){
  tryCatch({cat('mean of',colnames(p1_df)[i],'is',mean(pull(p1_df,i)),'\n')}, 
           #try calculate mean for ith variable in p1_df
           warning = function(w){
             cat(colnames(p1_df)[i],'variable in the dataframe doesn\'t work for mean','\n')
           #show the variable name if it doesn't work for mean
           }
  )
}
#for each variable in p1_df, calculate their mean, and shows which doesn't work

```
```{r, results='hide'}
as.numeric(0.3)
as.numeric(TRUE)
as.numeric('pancake')
as.numeric(factor('old','young'))
#character and factor can't convert to numeric variables so they don't work for mean
```

