P8105\_hm1\_kh3074
================

``` r
#import all the packages needed
library(tidyverse)
```

    ## ── Attaching packages ─────────────────────────────────────── tidyverse 1.3.1 ──

    ## ✓ ggplot2 3.3.5     ✓ purrr   0.3.4
    ## ✓ tibble  3.1.2     ✓ dplyr   1.0.7
    ## ✓ tidyr   1.1.3     ✓ stringr 1.4.0
    ## ✓ readr   2.0.1     ✓ forcats 0.5.1

    ## ── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──
    ## x dplyr::filter() masks stats::filter()
    ## x dplyr::lag()    masks stats::lag()

``` r
library(palmerpenguins)
```

------------------------------------------------------------------------

# Problem 1

## Create dataframe

``` r
p1_var1 = rnorm(10,mean = 0,sd = 1)
#create a random sample of size 10 from a standard Normal distribution
p1_var2 = p1_var1 > 0 
#create a logical vector indicating whether elements of the sample are greater than 0
p1_var3 = c('I','love','pancake','and','I','don\'t','know','what','I\'m','saying')
#create a character vector of length 10
p1_var4 = factor(c('old','young','baby','old','young','baby','old','young','baby','young'))
#a factor vector of length 10, with 3 different factor “levels”
p1_df = tibble(
  p1_var1,
  p1_var2,
  p1_var3,
  p1_var4
)
#put all the four variables in to a dataframe
p1_df
```

    ## # A tibble: 10 x 4
    ##    p1_var1 p1_var2 p1_var3 p1_var4
    ##      <dbl> <lgl>   <chr>   <fct>  
    ##  1  -0.488 FALSE   I       old    
    ##  2  -1.37  FALSE   love    young  
    ##  3   0.276 TRUE    pancake baby   
    ##  4  -0.692 FALSE   and     old    
    ##  5  -0.934 FALSE   I       young  
    ##  6  -1.84  FALSE   don't   baby   
    ##  7  -0.917 FALSE   know    old    
    ##  8  -1.92  FALSE   what    young  
    ##  9   0.694 TRUE    I'm     baby   
    ## 10  -0.167 FALSE   saying  young

## caculate mean

``` r
for (i in 1:length(p1_df)){
  tryCatch({cat('mean of',colnames(p1_df)[i],'is',mean(pull(p1_df,i)),'\n')}, 
           #try calculate mean for ith variable in p1_df
           warning = function(w){
           cat(colnames(p1_df)[i],'variable in the dataframe doesn\'t work for mean','\n')
           #show the variable name if it doesn't work for mean
           }
  )
}
```

    ## mean of p1_var1 is -0.7369655 
    ## mean of p1_var2 is 0.2 
    ## p1_var3 variable in the dataframe doesn't work for mean 
    ## p1_var4 variable in the dataframe doesn't work for mean

## try convert variables to numeric

``` r
as.numeric(0.3)
as.numeric(TRUE)
as.numeric('pancake')
```

    ## Warning: NAs introduced by coercion

``` r
as.numeric(factor('old','young'))
```

Float variable and logistic variable can successfully convert to numeric
variables  
Factor variable and character variable get NA  
Conclusion: character and factor can’t convert to numeric variables so
they don’t work for mean

------------------------------------------------------------------------

# Problem 2

## load penguins dataset

``` r
df = data(penguins,package = 'palmerpenguins')
penguins
```

    ## # A tibble: 344 x 8
    ##    species island    bill_length_mm bill_depth_mm flipper_length_mm body_mass_g
    ##    <fct>   <fct>              <dbl>         <dbl>             <int>       <int>
    ##  1 Adelie  Torgersen           39.1          18.7               181        3750
    ##  2 Adelie  Torgersen           39.5          17.4               186        3800
    ##  3 Adelie  Torgersen           40.3          18                 195        3250
    ##  4 Adelie  Torgersen           NA            NA                  NA          NA
    ##  5 Adelie  Torgersen           36.7          19.3               193        3450
    ##  6 Adelie  Torgersen           39.3          20.6               190        3650
    ##  7 Adelie  Torgersen           38.9          17.8               181        3625
    ##  8 Adelie  Torgersen           39.2          19.6               195        4675
    ##  9 Adelie  Torgersen           34.1          18.1               193        3475
    ## 10 Adelie  Torgersen           42            20.2               190        4250
    ## # … with 334 more rows, and 2 more variables: sex <fct>, year <int>

``` r
summary(penguins)
```

    ##       species          island    bill_length_mm  bill_depth_mm  
    ##  Adelie   :152   Biscoe   :168   Min.   :32.10   Min.   :13.10  
    ##  Chinstrap: 68   Dream    :124   1st Qu.:39.23   1st Qu.:15.60  
    ##  Gentoo   :124   Torgersen: 52   Median :44.45   Median :17.30  
    ##                                  Mean   :43.92   Mean   :17.15  
    ##                                  3rd Qu.:48.50   3rd Qu.:18.70  
    ##                                  Max.   :59.60   Max.   :21.50  
    ##                                  NA's   :2       NA's   :2      
    ##  flipper_length_mm  body_mass_g       sex           year     
    ##  Min.   :172.0     Min.   :2700   female:165   Min.   :2007  
    ##  1st Qu.:190.0     1st Qu.:3550   male  :168   1st Qu.:2007  
    ##  Median :197.0     Median :4050   NA's  : 11   Median :2008  
    ##  Mean   :200.9     Mean   :4202                Mean   :2008  
    ##  3rd Qu.:213.0     3rd Qu.:4750                3rd Qu.:2009  
    ##  Max.   :231.0     Max.   :6300                Max.   :2009  
    ##  NA's   :2         NA's   :2

## describe the dataset

``` r
colnames(penguins)
```

    ## [1] "species"           "island"            "bill_length_mm"   
    ## [4] "bill_depth_mm"     "flipper_length_mm" "body_mass_g"      
    ## [7] "sex"               "year"

here are total 344 penguins in the data set and each of them have 8
features

``` r
table(penguins[1])
```

    ## 
    ##    Adelie Chinstrap    Gentoo 
    ##       152        68       124

species is a **factor** variables which contain 3 “levels”,there are 152
Adelies,68 Chinstraps and 124 Gentoos

``` r
table(penguins[2])
```

    ## 
    ##    Biscoe     Dream Torgersen 
    ##       168       124        52

island is a **factor** variables which contain 3 “levels”,there are 168
Biscoe,124 Dream and 52 Torgersen

``` r
sum(is.na(pull(penguins,3)))
```

    ## [1] 2

``` r
#find the missing value
```

“bill\_length\_mm”and “bill\_depth\_mm”are **float** variables  
“flipper\_length\_mm”and “body\_mass\_g” are **int** variables  
**There are two penguins lost these four values**

``` r
sum(is.na(pull(penguins,7)))
```

    ## [1] 11

sex is a **factor** variable which contain 2 “levels”,there are 165
femals,and 168 males **(11 NAs)**

``` r
table(penguins[8])
```

    ## 
    ## 2007 2008 2009 
    ##  110  114  120

All the penguins are observed during 2007,2008,2009

## The size of the dataset

``` r
ncol(penguins)
```

    ## [1] 8

``` r
nrow(penguins)
```

    ## [1] 344

There are **344** penguins recorded and each of them have **8** features

## The mean of flipper length

**there are 2 missing values in the vector “flipper\_length\_mm”** We
should ignore the two missing values when we calculate the mean.

``` r
mean(pull(penguins,5),na.rm = TRUE)
```

    ## [1] 200.9152

The mean flipper length is 200.9152

## Draw the scatterplot

``` r
ggplot(penguins,aes(x = bill_length_mm,y = flipper_length_mm, colour = species)) + geom_point()
```

    ## Warning: Removed 2 rows containing missing values (geom_point).

![](P8105_hw1_kh3074_files/figure-gfm/unnamed-chunk-14-1.png)<!-- -->

``` r
ggsave('penguin plot.png')
```

    ## Saving 7 x 5 in image

    ## Warning: Removed 2 rows containing missing values (geom_point).
